export const REFRESH_USER_INFORMATION_SUCCESS = 'REFRESH_USER_INFORMATION_SUCCESS';
export const REFRESH_USER_INFORMATION_ERROR = 'REFRESH_USER_INFORMATION_ERROR';
export const REFRESH_USER_INFORMATION_REQUEST = 'REFRESH_USER_INFORMATION_REQUEST';
export const REFRESH_REPOSITORIES = 'REFRESH_REPOSITORIES';
export const REFRESH_LANGUAGES = 'REFRESH_LANGUAGES';
